#!/bin/bash

rm -rvf world

world_shp() {
  mkdir -p build
  curl -o build/ne_$1_admin_0_countries.zip http://naciscdn.org/naturalearth/$1/cultural/ne_$1_admin_0_countries.zip
  unzip -od build build/ne_$1_admin_0_countries.zip
  chmod a-x build/ne_$1_admin_0_countries.*
}

world() {
  world_shp $1
  mkdir -p world
  geo2topo -q 1e5 -n countries=<( \
      shp2json -n build/ne_$1_admin_0_countries.shp \
        | ndjson-map 'i = d.properties.iso_n3, d.id = i === "-99" ? undefined : i, delete d.properties, d' \
        | geostitch -n) \
    | topomerge land=countries \
    > world/$1.json

  if ! [ -x "$(command -v json2tsv)" ]; then
    echo "Error: json2tsv was not found. world/$1.tsv not created." >&2
  else
    shp2json -n build/ne_$1_admin_0_countries.shp \
      | ndjson-map 'd.properties' \
      | ndjson-sort 'a.iso_a3.localeCompare(b.iso_a3)' \
      | json2tsv -n \
      > world/$1.tsv
  fi
}

world 110m
world 50m
world 10m
